deps.minecraft=1.6.4
deps.yarn-build=604
deps.fabric-loader=0.19.3
fabric_loader_min_version=0.16.0
java_version=8
mixin_compatibility_level=JAVA_8
sprint_mixin=LegacyClientPlayerNoSprintKeyMixin
movement_mixin=LegacyLivingEntityClassicMixin
jump_mixin=LegacyLivingEntityJumpMixin
command_mixin=LegacyClientCommandEarlyMixin
