org.gradle.jvmargs=-Xmx4G -Djava.io.tmpdir=G:/omni-rebuilt/.tmp
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=omni
mod.name=Omni
mod.version=1.2-OVERHAUL
mod.description=Allows sprinting in any movement direction while still using vanilla sprint rules. Inspired by Black Ops 6 and The Finals.
mod.author=AvacadoWizard120
mod.sources=https://github.com/AvacadoWizard120/Omni
mod.issues=https://github.com/AvacadoWizard120/Omni/issues
mod.homepage=https://modrinth.com/mod/omnidirectional-movement
mod.license=MIT
mod.icon=assets/omni/icon.png
mod.group=io.github.avacadowizard120
